# Generated by Django 4.0.5 on 2022-10-13 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notes.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_rename_category_note_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=notes.fields.NonStrippingTextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
